
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Schema` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Schema
 * 
 */
export type SchemaModel = runtime.Types.Result.DefaultSelection<Prisma.$SchemaPayload>

export type AggregateSchema = {
  _count: SchemaCountAggregateOutputType | null
  _avg: SchemaAvgAggregateOutputType | null
  _sum: SchemaSumAggregateOutputType | null
  _min: SchemaMinAggregateOutputType | null
  _max: SchemaMaxAggregateOutputType | null
}

export type SchemaAvgAggregateOutputType = {
  version: number | null
}

export type SchemaSumAggregateOutputType = {
  version: number | null
}

export type SchemaMinAggregateOutputType = {
  id: string | null
  ownerId: string | null
  name: string | null
  version: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SchemaMaxAggregateOutputType = {
  id: string | null
  ownerId: string | null
  name: string | null
  version: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SchemaCountAggregateOutputType = {
  id: number
  ownerId: number
  name: number
  version: number
  jsonSchema: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type SchemaAvgAggregateInputType = {
  version?: true
}

export type SchemaSumAggregateInputType = {
  version?: true
}

export type SchemaMinAggregateInputType = {
  id?: true
  ownerId?: true
  name?: true
  version?: true
  createdAt?: true
  updatedAt?: true
}

export type SchemaMaxAggregateInputType = {
  id?: true
  ownerId?: true
  name?: true
  version?: true
  createdAt?: true
  updatedAt?: true
}

export type SchemaCountAggregateInputType = {
  id?: true
  ownerId?: true
  name?: true
  version?: true
  jsonSchema?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type SchemaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Schema to aggregate.
   */
  where?: Prisma.SchemaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Schemata to fetch.
   */
  orderBy?: Prisma.SchemaOrderByWithRelationInput | Prisma.SchemaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SchemaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Schemata from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Schemata.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Schemata
  **/
  _count?: true | SchemaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SchemaAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SchemaSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SchemaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SchemaMaxAggregateInputType
}

export type GetSchemaAggregateType<T extends SchemaAggregateArgs> = {
      [P in keyof T & keyof AggregateSchema]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSchema[P]>
    : Prisma.GetScalarType<T[P], AggregateSchema[P]>
}




export type SchemaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SchemaWhereInput
  orderBy?: Prisma.SchemaOrderByWithAggregationInput | Prisma.SchemaOrderByWithAggregationInput[]
  by: Prisma.SchemaScalarFieldEnum[] | Prisma.SchemaScalarFieldEnum
  having?: Prisma.SchemaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SchemaCountAggregateInputType | true
  _avg?: SchemaAvgAggregateInputType
  _sum?: SchemaSumAggregateInputType
  _min?: SchemaMinAggregateInputType
  _max?: SchemaMaxAggregateInputType
}

export type SchemaGroupByOutputType = {
  id: string
  ownerId: string
  name: string
  version: number
  jsonSchema: runtime.JsonValue
  createdAt: Date
  updatedAt: Date
  _count: SchemaCountAggregateOutputType | null
  _avg: SchemaAvgAggregateOutputType | null
  _sum: SchemaSumAggregateOutputType | null
  _min: SchemaMinAggregateOutputType | null
  _max: SchemaMaxAggregateOutputType | null
}

export type GetSchemaGroupByPayload<T extends SchemaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SchemaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SchemaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SchemaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SchemaGroupByOutputType[P]>
      }
    >
  >



export type SchemaWhereInput = {
  AND?: Prisma.SchemaWhereInput | Prisma.SchemaWhereInput[]
  OR?: Prisma.SchemaWhereInput[]
  NOT?: Prisma.SchemaWhereInput | Prisma.SchemaWhereInput[]
  id?: Prisma.StringFilter<"Schema"> | string
  ownerId?: Prisma.StringFilter<"Schema"> | string
  name?: Prisma.StringFilter<"Schema"> | string
  version?: Prisma.IntFilter<"Schema"> | number
  jsonSchema?: Prisma.JsonFilter<"Schema">
  createdAt?: Prisma.DateTimeFilter<"Schema"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Schema"> | Date | string
  owner?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>
  folders?: Prisma.FolderListRelationFilter
}

export type SchemaOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  version?: Prisma.SortOrder
  jsonSchema?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  owner?: Prisma.AccountOrderByWithRelationInput
  folders?: Prisma.FolderOrderByRelationAggregateInput
}

export type SchemaWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SchemaWhereInput | Prisma.SchemaWhereInput[]
  OR?: Prisma.SchemaWhereInput[]
  NOT?: Prisma.SchemaWhereInput | Prisma.SchemaWhereInput[]
  ownerId?: Prisma.StringFilter<"Schema"> | string
  name?: Prisma.StringFilter<"Schema"> | string
  version?: Prisma.IntFilter<"Schema"> | number
  jsonSchema?: Prisma.JsonFilter<"Schema">
  createdAt?: Prisma.DateTimeFilter<"Schema"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Schema"> | Date | string
  owner?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>
  folders?: Prisma.FolderListRelationFilter
}, "id">

export type SchemaOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  version?: Prisma.SortOrder
  jsonSchema?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.SchemaCountOrderByAggregateInput
  _avg?: Prisma.SchemaAvgOrderByAggregateInput
  _max?: Prisma.SchemaMaxOrderByAggregateInput
  _min?: Prisma.SchemaMinOrderByAggregateInput
  _sum?: Prisma.SchemaSumOrderByAggregateInput
}

export type SchemaScalarWhereWithAggregatesInput = {
  AND?: Prisma.SchemaScalarWhereWithAggregatesInput | Prisma.SchemaScalarWhereWithAggregatesInput[]
  OR?: Prisma.SchemaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SchemaScalarWhereWithAggregatesInput | Prisma.SchemaScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Schema"> | string
  ownerId?: Prisma.StringWithAggregatesFilter<"Schema"> | string
  name?: Prisma.StringWithAggregatesFilter<"Schema"> | string
  version?: Prisma.IntWithAggregatesFilter<"Schema"> | number
  jsonSchema?: Prisma.JsonWithAggregatesFilter<"Schema">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Schema"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Schema"> | Date | string
}

export type SchemaCreateInput = {
  id?: string
  name: string
  version: number
  jsonSchema: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  owner: Prisma.AccountCreateNestedOneWithoutSchemasInput
  folders?: Prisma.FolderCreateNestedManyWithoutSchemaInput
}

export type SchemaUncheckedCreateInput = {
  id?: string
  ownerId: string
  name: string
  version: number
  jsonSchema: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  folders?: Prisma.FolderUncheckedCreateNestedManyWithoutSchemaInput
}

export type SchemaUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  jsonSchema?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner?: Prisma.AccountUpdateOneRequiredWithoutSchemasNestedInput
  folders?: Prisma.FolderUpdateManyWithoutSchemaNestedInput
}

export type SchemaUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  jsonSchema?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  folders?: Prisma.FolderUncheckedUpdateManyWithoutSchemaNestedInput
}

export type SchemaCreateManyInput = {
  id?: string
  ownerId: string
  name: string
  version: number
  jsonSchema: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SchemaUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  jsonSchema?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SchemaUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  jsonSchema?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SchemaListRelationFilter = {
  every?: Prisma.SchemaWhereInput
  some?: Prisma.SchemaWhereInput
  none?: Prisma.SchemaWhereInput
}

export type SchemaOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SchemaCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  version?: Prisma.SortOrder
  jsonSchema?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SchemaAvgOrderByAggregateInput = {
  version?: Prisma.SortOrder
}

export type SchemaMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  version?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SchemaMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  version?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SchemaSumOrderByAggregateInput = {
  version?: Prisma.SortOrder
}

export type SchemaScalarRelationFilter = {
  is?: Prisma.SchemaWhereInput
  isNot?: Prisma.SchemaWhereInput
}

export type SchemaCreateNestedManyWithoutOwnerInput = {
  create?: Prisma.XOR<Prisma.SchemaCreateWithoutOwnerInput, Prisma.SchemaUncheckedCreateWithoutOwnerInput> | Prisma.SchemaCreateWithoutOwnerInput[] | Prisma.SchemaUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.SchemaCreateOrConnectWithoutOwnerInput | Prisma.SchemaCreateOrConnectWithoutOwnerInput[]
  createMany?: Prisma.SchemaCreateManyOwnerInputEnvelope
  connect?: Prisma.SchemaWhereUniqueInput | Prisma.SchemaWhereUniqueInput[]
}

export type SchemaUncheckedCreateNestedManyWithoutOwnerInput = {
  create?: Prisma.XOR<Prisma.SchemaCreateWithoutOwnerInput, Prisma.SchemaUncheckedCreateWithoutOwnerInput> | Prisma.SchemaCreateWithoutOwnerInput[] | Prisma.SchemaUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.SchemaCreateOrConnectWithoutOwnerInput | Prisma.SchemaCreateOrConnectWithoutOwnerInput[]
  createMany?: Prisma.SchemaCreateManyOwnerInputEnvelope
  connect?: Prisma.SchemaWhereUniqueInput | Prisma.SchemaWhereUniqueInput[]
}

export type SchemaUpdateManyWithoutOwnerNestedInput = {
  create?: Prisma.XOR<Prisma.SchemaCreateWithoutOwnerInput, Prisma.SchemaUncheckedCreateWithoutOwnerInput> | Prisma.SchemaCreateWithoutOwnerInput[] | Prisma.SchemaUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.SchemaCreateOrConnectWithoutOwnerInput | Prisma.SchemaCreateOrConnectWithoutOwnerInput[]
  upsert?: Prisma.SchemaUpsertWithWhereUniqueWithoutOwnerInput | Prisma.SchemaUpsertWithWhereUniqueWithoutOwnerInput[]
  createMany?: Prisma.SchemaCreateManyOwnerInputEnvelope
  set?: Prisma.SchemaWhereUniqueInput | Prisma.SchemaWhereUniqueInput[]
  disconnect?: Prisma.SchemaWhereUniqueInput | Prisma.SchemaWhereUniqueInput[]
  delete?: Prisma.SchemaWhereUniqueInput | Prisma.SchemaWhereUniqueInput[]
  connect?: Prisma.SchemaWhereUniqueInput | Prisma.SchemaWhereUniqueInput[]
  update?: Prisma.SchemaUpdateWithWhereUniqueWithoutOwnerInput | Prisma.SchemaUpdateWithWhereUniqueWithoutOwnerInput[]
  updateMany?: Prisma.SchemaUpdateManyWithWhereWithoutOwnerInput | Prisma.SchemaUpdateManyWithWhereWithoutOwnerInput[]
  deleteMany?: Prisma.SchemaScalarWhereInput | Prisma.SchemaScalarWhereInput[]
}

export type SchemaUncheckedUpdateManyWithoutOwnerNestedInput = {
  create?: Prisma.XOR<Prisma.SchemaCreateWithoutOwnerInput, Prisma.SchemaUncheckedCreateWithoutOwnerInput> | Prisma.SchemaCreateWithoutOwnerInput[] | Prisma.SchemaUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.SchemaCreateOrConnectWithoutOwnerInput | Prisma.SchemaCreateOrConnectWithoutOwnerInput[]
  upsert?: Prisma.SchemaUpsertWithWhereUniqueWithoutOwnerInput | Prisma.SchemaUpsertWithWhereUniqueWithoutOwnerInput[]
  createMany?: Prisma.SchemaCreateManyOwnerInputEnvelope
  set?: Prisma.SchemaWhereUniqueInput | Prisma.SchemaWhereUniqueInput[]
  disconnect?: Prisma.SchemaWhereUniqueInput | Prisma.SchemaWhereUniqueInput[]
  delete?: Prisma.SchemaWhereUniqueInput | Prisma.SchemaWhereUniqueInput[]
  connect?: Prisma.SchemaWhereUniqueInput | Prisma.SchemaWhereUniqueInput[]
  update?: Prisma.SchemaUpdateWithWhereUniqueWithoutOwnerInput | Prisma.SchemaUpdateWithWhereUniqueWithoutOwnerInput[]
  updateMany?: Prisma.SchemaUpdateManyWithWhereWithoutOwnerInput | Prisma.SchemaUpdateManyWithWhereWithoutOwnerInput[]
  deleteMany?: Prisma.SchemaScalarWhereInput | Prisma.SchemaScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type SchemaCreateNestedOneWithoutFoldersInput = {
  create?: Prisma.XOR<Prisma.SchemaCreateWithoutFoldersInput, Prisma.SchemaUncheckedCreateWithoutFoldersInput>
  connectOrCreate?: Prisma.SchemaCreateOrConnectWithoutFoldersInput
  connect?: Prisma.SchemaWhereUniqueInput
}

export type SchemaUpdateOneRequiredWithoutFoldersNestedInput = {
  create?: Prisma.XOR<Prisma.SchemaCreateWithoutFoldersInput, Prisma.SchemaUncheckedCreateWithoutFoldersInput>
  connectOrCreate?: Prisma.SchemaCreateOrConnectWithoutFoldersInput
  upsert?: Prisma.SchemaUpsertWithoutFoldersInput
  connect?: Prisma.SchemaWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SchemaUpdateToOneWithWhereWithoutFoldersInput, Prisma.SchemaUpdateWithoutFoldersInput>, Prisma.SchemaUncheckedUpdateWithoutFoldersInput>
}

export type SchemaCreateWithoutOwnerInput = {
  id?: string
  name: string
  version: number
  jsonSchema: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  folders?: Prisma.FolderCreateNestedManyWithoutSchemaInput
}

export type SchemaUncheckedCreateWithoutOwnerInput = {
  id?: string
  name: string
  version: number
  jsonSchema: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  folders?: Prisma.FolderUncheckedCreateNestedManyWithoutSchemaInput
}

export type SchemaCreateOrConnectWithoutOwnerInput = {
  where: Prisma.SchemaWhereUniqueInput
  create: Prisma.XOR<Prisma.SchemaCreateWithoutOwnerInput, Prisma.SchemaUncheckedCreateWithoutOwnerInput>
}

export type SchemaCreateManyOwnerInputEnvelope = {
  data: Prisma.SchemaCreateManyOwnerInput | Prisma.SchemaCreateManyOwnerInput[]
  skipDuplicates?: boolean
}

export type SchemaUpsertWithWhereUniqueWithoutOwnerInput = {
  where: Prisma.SchemaWhereUniqueInput
  update: Prisma.XOR<Prisma.SchemaUpdateWithoutOwnerInput, Prisma.SchemaUncheckedUpdateWithoutOwnerInput>
  create: Prisma.XOR<Prisma.SchemaCreateWithoutOwnerInput, Prisma.SchemaUncheckedCreateWithoutOwnerInput>
}

export type SchemaUpdateWithWhereUniqueWithoutOwnerInput = {
  where: Prisma.SchemaWhereUniqueInput
  data: Prisma.XOR<Prisma.SchemaUpdateWithoutOwnerInput, Prisma.SchemaUncheckedUpdateWithoutOwnerInput>
}

export type SchemaUpdateManyWithWhereWithoutOwnerInput = {
  where: Prisma.SchemaScalarWhereInput
  data: Prisma.XOR<Prisma.SchemaUpdateManyMutationInput, Prisma.SchemaUncheckedUpdateManyWithoutOwnerInput>
}

export type SchemaScalarWhereInput = {
  AND?: Prisma.SchemaScalarWhereInput | Prisma.SchemaScalarWhereInput[]
  OR?: Prisma.SchemaScalarWhereInput[]
  NOT?: Prisma.SchemaScalarWhereInput | Prisma.SchemaScalarWhereInput[]
  id?: Prisma.StringFilter<"Schema"> | string
  ownerId?: Prisma.StringFilter<"Schema"> | string
  name?: Prisma.StringFilter<"Schema"> | string
  version?: Prisma.IntFilter<"Schema"> | number
  jsonSchema?: Prisma.JsonFilter<"Schema">
  createdAt?: Prisma.DateTimeFilter<"Schema"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Schema"> | Date | string
}

export type SchemaCreateWithoutFoldersInput = {
  id?: string
  name: string
  version: number
  jsonSchema: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  owner: Prisma.AccountCreateNestedOneWithoutSchemasInput
}

export type SchemaUncheckedCreateWithoutFoldersInput = {
  id?: string
  ownerId: string
  name: string
  version: number
  jsonSchema: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SchemaCreateOrConnectWithoutFoldersInput = {
  where: Prisma.SchemaWhereUniqueInput
  create: Prisma.XOR<Prisma.SchemaCreateWithoutFoldersInput, Prisma.SchemaUncheckedCreateWithoutFoldersInput>
}

export type SchemaUpsertWithoutFoldersInput = {
  update: Prisma.XOR<Prisma.SchemaUpdateWithoutFoldersInput, Prisma.SchemaUncheckedUpdateWithoutFoldersInput>
  create: Prisma.XOR<Prisma.SchemaCreateWithoutFoldersInput, Prisma.SchemaUncheckedCreateWithoutFoldersInput>
  where?: Prisma.SchemaWhereInput
}

export type SchemaUpdateToOneWithWhereWithoutFoldersInput = {
  where?: Prisma.SchemaWhereInput
  data: Prisma.XOR<Prisma.SchemaUpdateWithoutFoldersInput, Prisma.SchemaUncheckedUpdateWithoutFoldersInput>
}

export type SchemaUpdateWithoutFoldersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  jsonSchema?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner?: Prisma.AccountUpdateOneRequiredWithoutSchemasNestedInput
}

export type SchemaUncheckedUpdateWithoutFoldersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  jsonSchema?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SchemaCreateManyOwnerInput = {
  id?: string
  name: string
  version: number
  jsonSchema: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SchemaUpdateWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  jsonSchema?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  folders?: Prisma.FolderUpdateManyWithoutSchemaNestedInput
}

export type SchemaUncheckedUpdateWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  jsonSchema?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  folders?: Prisma.FolderUncheckedUpdateManyWithoutSchemaNestedInput
}

export type SchemaUncheckedUpdateManyWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  jsonSchema?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type SchemaCountOutputType
 */

export type SchemaCountOutputType = {
  folders: number
}

export type SchemaCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  folders?: boolean | SchemaCountOutputTypeCountFoldersArgs
}

/**
 * SchemaCountOutputType without action
 */
export type SchemaCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SchemaCountOutputType
   */
  select?: Prisma.SchemaCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SchemaCountOutputType without action
 */
export type SchemaCountOutputTypeCountFoldersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FolderWhereInput
}


export type SchemaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ownerId?: boolean
  name?: boolean
  version?: boolean
  jsonSchema?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  owner?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
  folders?: boolean | Prisma.Schema$foldersArgs<ExtArgs>
  _count?: boolean | Prisma.SchemaCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["schema"]>

export type SchemaSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ownerId?: boolean
  name?: boolean
  version?: boolean
  jsonSchema?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  owner?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["schema"]>

export type SchemaSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ownerId?: boolean
  name?: boolean
  version?: boolean
  jsonSchema?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  owner?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["schema"]>

export type SchemaSelectScalar = {
  id?: boolean
  ownerId?: boolean
  name?: boolean
  version?: boolean
  jsonSchema?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type SchemaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "ownerId" | "name" | "version" | "jsonSchema" | "createdAt" | "updatedAt", ExtArgs["result"]["schema"]>
export type SchemaInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  owner?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
  folders?: boolean | Prisma.Schema$foldersArgs<ExtArgs>
  _count?: boolean | Prisma.SchemaCountOutputTypeDefaultArgs<ExtArgs>
}
export type SchemaIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  owner?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
}
export type SchemaIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  owner?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
}

export type $SchemaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Schema"
  objects: {
    owner: Prisma.$AccountPayload<ExtArgs>
    folders: Prisma.$FolderPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    ownerId: string
    name: string
    version: number
    jsonSchema: runtime.JsonValue
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["schema"]>
  composites: {}
}

export type SchemaGetPayload<S extends boolean | null | undefined | SchemaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SchemaPayload, S>

export type SchemaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SchemaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SchemaCountAggregateInputType | true
  }

export interface SchemaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Schema'], meta: { name: 'Schema' } }
  /**
   * Find zero or one Schema that matches the filter.
   * @param {SchemaFindUniqueArgs} args - Arguments to find a Schema
   * @example
   * // Get one Schema
   * const schema = await prisma.schema.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SchemaFindUniqueArgs>(args: Prisma.SelectSubset<T, SchemaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SchemaClient<runtime.Types.Result.GetResult<Prisma.$SchemaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Schema that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SchemaFindUniqueOrThrowArgs} args - Arguments to find a Schema
   * @example
   * // Get one Schema
   * const schema = await prisma.schema.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SchemaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SchemaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SchemaClient<runtime.Types.Result.GetResult<Prisma.$SchemaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Schema that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SchemaFindFirstArgs} args - Arguments to find a Schema
   * @example
   * // Get one Schema
   * const schema = await prisma.schema.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SchemaFindFirstArgs>(args?: Prisma.SelectSubset<T, SchemaFindFirstArgs<ExtArgs>>): Prisma.Prisma__SchemaClient<runtime.Types.Result.GetResult<Prisma.$SchemaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Schema that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SchemaFindFirstOrThrowArgs} args - Arguments to find a Schema
   * @example
   * // Get one Schema
   * const schema = await prisma.schema.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SchemaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SchemaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SchemaClient<runtime.Types.Result.GetResult<Prisma.$SchemaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Schemata that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SchemaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Schemata
   * const schemata = await prisma.schema.findMany()
   * 
   * // Get first 10 Schemata
   * const schemata = await prisma.schema.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const schemaWithIdOnly = await prisma.schema.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SchemaFindManyArgs>(args?: Prisma.SelectSubset<T, SchemaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SchemaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Schema.
   * @param {SchemaCreateArgs} args - Arguments to create a Schema.
   * @example
   * // Create one Schema
   * const Schema = await prisma.schema.create({
   *   data: {
   *     // ... data to create a Schema
   *   }
   * })
   * 
   */
  create<T extends SchemaCreateArgs>(args: Prisma.SelectSubset<T, SchemaCreateArgs<ExtArgs>>): Prisma.Prisma__SchemaClient<runtime.Types.Result.GetResult<Prisma.$SchemaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Schemata.
   * @param {SchemaCreateManyArgs} args - Arguments to create many Schemata.
   * @example
   * // Create many Schemata
   * const schema = await prisma.schema.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SchemaCreateManyArgs>(args?: Prisma.SelectSubset<T, SchemaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Schemata and returns the data saved in the database.
   * @param {SchemaCreateManyAndReturnArgs} args - Arguments to create many Schemata.
   * @example
   * // Create many Schemata
   * const schema = await prisma.schema.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Schemata and only return the `id`
   * const schemaWithIdOnly = await prisma.schema.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SchemaCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SchemaCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SchemaPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Schema.
   * @param {SchemaDeleteArgs} args - Arguments to delete one Schema.
   * @example
   * // Delete one Schema
   * const Schema = await prisma.schema.delete({
   *   where: {
   *     // ... filter to delete one Schema
   *   }
   * })
   * 
   */
  delete<T extends SchemaDeleteArgs>(args: Prisma.SelectSubset<T, SchemaDeleteArgs<ExtArgs>>): Prisma.Prisma__SchemaClient<runtime.Types.Result.GetResult<Prisma.$SchemaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Schema.
   * @param {SchemaUpdateArgs} args - Arguments to update one Schema.
   * @example
   * // Update one Schema
   * const schema = await prisma.schema.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SchemaUpdateArgs>(args: Prisma.SelectSubset<T, SchemaUpdateArgs<ExtArgs>>): Prisma.Prisma__SchemaClient<runtime.Types.Result.GetResult<Prisma.$SchemaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Schemata.
   * @param {SchemaDeleteManyArgs} args - Arguments to filter Schemata to delete.
   * @example
   * // Delete a few Schemata
   * const { count } = await prisma.schema.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SchemaDeleteManyArgs>(args?: Prisma.SelectSubset<T, SchemaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Schemata.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SchemaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Schemata
   * const schema = await prisma.schema.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SchemaUpdateManyArgs>(args: Prisma.SelectSubset<T, SchemaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Schemata and returns the data updated in the database.
   * @param {SchemaUpdateManyAndReturnArgs} args - Arguments to update many Schemata.
   * @example
   * // Update many Schemata
   * const schema = await prisma.schema.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Schemata and only return the `id`
   * const schemaWithIdOnly = await prisma.schema.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SchemaUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SchemaUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SchemaPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Schema.
   * @param {SchemaUpsertArgs} args - Arguments to update or create a Schema.
   * @example
   * // Update or create a Schema
   * const schema = await prisma.schema.upsert({
   *   create: {
   *     // ... data to create a Schema
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Schema we want to update
   *   }
   * })
   */
  upsert<T extends SchemaUpsertArgs>(args: Prisma.SelectSubset<T, SchemaUpsertArgs<ExtArgs>>): Prisma.Prisma__SchemaClient<runtime.Types.Result.GetResult<Prisma.$SchemaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Schemata.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SchemaCountArgs} args - Arguments to filter Schemata to count.
   * @example
   * // Count the number of Schemata
   * const count = await prisma.schema.count({
   *   where: {
   *     // ... the filter for the Schemata we want to count
   *   }
   * })
  **/
  count<T extends SchemaCountArgs>(
    args?: Prisma.Subset<T, SchemaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SchemaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Schema.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SchemaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SchemaAggregateArgs>(args: Prisma.Subset<T, SchemaAggregateArgs>): Prisma.PrismaPromise<GetSchemaAggregateType<T>>

  /**
   * Group by Schema.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SchemaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SchemaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SchemaGroupByArgs['orderBy'] }
      : { orderBy?: SchemaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SchemaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSchemaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Schema model
 */
readonly fields: SchemaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Schema.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SchemaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  owner<T extends Prisma.AccountDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AccountDefaultArgs<ExtArgs>>): Prisma.Prisma__AccountClient<runtime.Types.Result.GetResult<Prisma.$AccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  folders<T extends Prisma.Schema$foldersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Schema$foldersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FolderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Schema model
 */
export interface SchemaFieldRefs {
  readonly id: Prisma.FieldRef<"Schema", 'String'>
  readonly ownerId: Prisma.FieldRef<"Schema", 'String'>
  readonly name: Prisma.FieldRef<"Schema", 'String'>
  readonly version: Prisma.FieldRef<"Schema", 'Int'>
  readonly jsonSchema: Prisma.FieldRef<"Schema", 'Json'>
  readonly createdAt: Prisma.FieldRef<"Schema", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Schema", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Schema findUnique
 */
export type SchemaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Schema
   */
  select?: Prisma.SchemaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Schema
   */
  omit?: Prisma.SchemaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchemaInclude<ExtArgs> | null
  /**
   * Filter, which Schema to fetch.
   */
  where: Prisma.SchemaWhereUniqueInput
}

/**
 * Schema findUniqueOrThrow
 */
export type SchemaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Schema
   */
  select?: Prisma.SchemaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Schema
   */
  omit?: Prisma.SchemaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchemaInclude<ExtArgs> | null
  /**
   * Filter, which Schema to fetch.
   */
  where: Prisma.SchemaWhereUniqueInput
}

/**
 * Schema findFirst
 */
export type SchemaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Schema
   */
  select?: Prisma.SchemaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Schema
   */
  omit?: Prisma.SchemaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchemaInclude<ExtArgs> | null
  /**
   * Filter, which Schema to fetch.
   */
  where?: Prisma.SchemaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Schemata to fetch.
   */
  orderBy?: Prisma.SchemaOrderByWithRelationInput | Prisma.SchemaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Schemata.
   */
  cursor?: Prisma.SchemaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Schemata from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Schemata.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Schemata.
   */
  distinct?: Prisma.SchemaScalarFieldEnum | Prisma.SchemaScalarFieldEnum[]
}

/**
 * Schema findFirstOrThrow
 */
export type SchemaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Schema
   */
  select?: Prisma.SchemaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Schema
   */
  omit?: Prisma.SchemaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchemaInclude<ExtArgs> | null
  /**
   * Filter, which Schema to fetch.
   */
  where?: Prisma.SchemaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Schemata to fetch.
   */
  orderBy?: Prisma.SchemaOrderByWithRelationInput | Prisma.SchemaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Schemata.
   */
  cursor?: Prisma.SchemaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Schemata from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Schemata.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Schemata.
   */
  distinct?: Prisma.SchemaScalarFieldEnum | Prisma.SchemaScalarFieldEnum[]
}

/**
 * Schema findMany
 */
export type SchemaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Schema
   */
  select?: Prisma.SchemaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Schema
   */
  omit?: Prisma.SchemaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchemaInclude<ExtArgs> | null
  /**
   * Filter, which Schemata to fetch.
   */
  where?: Prisma.SchemaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Schemata to fetch.
   */
  orderBy?: Prisma.SchemaOrderByWithRelationInput | Prisma.SchemaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Schemata.
   */
  cursor?: Prisma.SchemaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Schemata from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Schemata.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Schemata.
   */
  distinct?: Prisma.SchemaScalarFieldEnum | Prisma.SchemaScalarFieldEnum[]
}

/**
 * Schema create
 */
export type SchemaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Schema
   */
  select?: Prisma.SchemaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Schema
   */
  omit?: Prisma.SchemaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchemaInclude<ExtArgs> | null
  /**
   * The data needed to create a Schema.
   */
  data: Prisma.XOR<Prisma.SchemaCreateInput, Prisma.SchemaUncheckedCreateInput>
}

/**
 * Schema createMany
 */
export type SchemaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Schemata.
   */
  data: Prisma.SchemaCreateManyInput | Prisma.SchemaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Schema createManyAndReturn
 */
export type SchemaCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Schema
   */
  select?: Prisma.SchemaSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Schema
   */
  omit?: Prisma.SchemaOmit<ExtArgs> | null
  /**
   * The data used to create many Schemata.
   */
  data: Prisma.SchemaCreateManyInput | Prisma.SchemaCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchemaIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Schema update
 */
export type SchemaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Schema
   */
  select?: Prisma.SchemaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Schema
   */
  omit?: Prisma.SchemaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchemaInclude<ExtArgs> | null
  /**
   * The data needed to update a Schema.
   */
  data: Prisma.XOR<Prisma.SchemaUpdateInput, Prisma.SchemaUncheckedUpdateInput>
  /**
   * Choose, which Schema to update.
   */
  where: Prisma.SchemaWhereUniqueInput
}

/**
 * Schema updateMany
 */
export type SchemaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Schemata.
   */
  data: Prisma.XOR<Prisma.SchemaUpdateManyMutationInput, Prisma.SchemaUncheckedUpdateManyInput>
  /**
   * Filter which Schemata to update
   */
  where?: Prisma.SchemaWhereInput
  /**
   * Limit how many Schemata to update.
   */
  limit?: number
}

/**
 * Schema updateManyAndReturn
 */
export type SchemaUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Schema
   */
  select?: Prisma.SchemaSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Schema
   */
  omit?: Prisma.SchemaOmit<ExtArgs> | null
  /**
   * The data used to update Schemata.
   */
  data: Prisma.XOR<Prisma.SchemaUpdateManyMutationInput, Prisma.SchemaUncheckedUpdateManyInput>
  /**
   * Filter which Schemata to update
   */
  where?: Prisma.SchemaWhereInput
  /**
   * Limit how many Schemata to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchemaIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Schema upsert
 */
export type SchemaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Schema
   */
  select?: Prisma.SchemaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Schema
   */
  omit?: Prisma.SchemaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchemaInclude<ExtArgs> | null
  /**
   * The filter to search for the Schema to update in case it exists.
   */
  where: Prisma.SchemaWhereUniqueInput
  /**
   * In case the Schema found by the `where` argument doesn't exist, create a new Schema with this data.
   */
  create: Prisma.XOR<Prisma.SchemaCreateInput, Prisma.SchemaUncheckedCreateInput>
  /**
   * In case the Schema was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SchemaUpdateInput, Prisma.SchemaUncheckedUpdateInput>
}

/**
 * Schema delete
 */
export type SchemaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Schema
   */
  select?: Prisma.SchemaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Schema
   */
  omit?: Prisma.SchemaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchemaInclude<ExtArgs> | null
  /**
   * Filter which Schema to delete.
   */
  where: Prisma.SchemaWhereUniqueInput
}

/**
 * Schema deleteMany
 */
export type SchemaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Schemata to delete
   */
  where?: Prisma.SchemaWhereInput
  /**
   * Limit how many Schemata to delete.
   */
  limit?: number
}

/**
 * Schema.folders
 */
export type Schema$foldersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folder
   */
  select?: Prisma.FolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Folder
   */
  omit?: Prisma.FolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FolderInclude<ExtArgs> | null
  where?: Prisma.FolderWhereInput
  orderBy?: Prisma.FolderOrderByWithRelationInput | Prisma.FolderOrderByWithRelationInput[]
  cursor?: Prisma.FolderWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FolderScalarFieldEnum | Prisma.FolderScalarFieldEnum[]
}

/**
 * Schema without action
 */
export type SchemaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Schema
   */
  select?: Prisma.SchemaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Schema
   */
  omit?: Prisma.SchemaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchemaInclude<ExtArgs> | null
}
